[tool.poetry]
name = "ai-py"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
langchain-core = "^1.2.7"
langchain = "^1.2.6"
langchain-openai = "^1.1.7"
langchain-community = "^0.4.1"
memory = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
